emacs-dashboard/emacs-dashboard

dashboard.el

- Add autoload cookie
- Remove spurious "ends here" line
- Fix header formatting, and improve commentary
- Fix page-break-lines dependency version
(I feel like `dashboard-insert-startupify-lists` should just be called `dashboard`, and also be autoloaded.)

Packaging fixes

---

README.org
dashboard.el

>[Give] the user 2 lists, one of pairs (:symbol . 'function), and another of :symbols, the first list defines the relationship between symbols (options) and the functions that will create them. The second will define the ordering of the elements. That way each user can define their own personal options easily.
From  https://github.com/rakanalh/emacs-dashboard/issues/8#issuecomment-258765120

[WIP] Allow startup list customization

---

dashboard.el

eval-when-compile should be used when a package uses only its macros.
This package uses its functions so eval-when-compile should not be used.

Remove needless eval-when-compile

---

.gitignore
Cask
dashboard-pkg.el
dashboard.el

Fixes #13 
* Adds content to buffer in `after-init-hook`
* Switches to buffer, enables `page-break-line-mode` and rendering in `emacs-startup-hook` 
* Adds Cask build system for developing packages (see individual commit messages below)

Ensures *dashboard* buffer exists at startup

---

dashboard.el

* Replace deprecated function with suggestion provided by emacs.
* Replace deprecated function with suggestion provided by emacs.
* Fix documentation errors reported by the default emacs-lisp checker.
* Wrapped a long line.
* Forward-delcare functions to keep linters happy.
(delcare-function can use 'ext:' prefix)
Supersedes #15

Keeps flycheck's emacs-lisp checker happy.

---

dashboard.el

If the banner contains an empty line (e.g. the first one in the bundled file), `dashboard-insert-ascii-banner-centered` inserts the centering spaces, which looks very bad with `global-whitespace-mode` highlighting spaces at the end of lines.  This patch fixes this probblem.

Don’t insert spaces in the banner if we are looking at an empty line

---

dashboard.el

This also works for any flag, for example emacs --debug-init , you probably dont want dashboard showing either ?

Dont show dashboard when command line arguments are present

---

dashboard-widgets.el

org-mode users can customize the display of org-agenda entries using
`org-agenda-prefix-format` (e.g., to show the filename, outline path, etc.). We
now apply the same formatting to the daily agenda shown in the dashboard.

org-agenda: format entries like org-agenda does

---

dashboard-widgets.el

Currently, when today’s agenda is empty, the agenda widget will display an empty
section framed by horizotal lines, with no header string, which will make it
look out of place and causes one to wonder whether something is broken.
We now always show the agenda section header and a «no entries» note so that
agenda display remains more consistent.

org-agenda: improve display when agenda is empty

---

README.org
dashboard-widgets.el
dashboard.el

This patch adds a new widget for displaying register lists. It uses `register-describe-oneline` to format each register. Its output might look like this: 
Registers:
z - file "~/.zshrc".
X - file "~/.Xresources".
x - file "~/.xinitrc".
t - file "~/.tmux.conf".
r - file "~/.ratpoisonrc".
The above only shows files, but the widget supports any register type, and will format it just as `register-list` would.

Add register widget

---

README.org
dashboard-widgets.el

Hi, this PR adds faces for widget headings and the banner title which allows for this kind of stuff:
Both of those faces are set to inherit from the `default` face by default so the initial look will remain the same.
It also adds an option to disable the banner title altogether by setting `dashboard-banner-logo-title` to `nil`.
Please do not hesitate to point out any mistakes I may have made or make any suggestions of your own!

Customizability improvements

---

dashboard-widgets.el

This PR causes banner images to be loaded with ImageMagick when Emacs is compiled `--with-imagemagick`.   Doing so extends support for additional file formats, and makes it possible to optionally resize the image while loading.
I needed this because my Emacs config grabs an "image of the day" from an external site and I want that image to be my dashboad banner, but I want to be flexible about the file formats and resolutions I might encounter in the wild.
Separately, I expect to create an "image of the day" widget as well.

load the banner image via imagemagick when available

---

dashboard.el

Hello, thanks for great plugin!
Here minor typo fix.
Signed-off-by: Pavel Kulyov <pkulev@croc.ru>

Fix commentary typo

---

README.org

On line 64, added a matching `"`  since single `"` isn't enough to load a png file (resulting in error).

Fixed typo

---

dashboard-widgets.el

This fixes dashboard crashing when it tries to insert a bookmark that does not have a filename parameter (e.g. elfeed bookmarks).

Fix dashboard crashing when bookmark isn't a file.

---

README.org

Otherwise dashboard fails to init properly and emacs displays: `Warning number of arguments: (lambda nil (insert "Custom text")), 1`

Custom generator must take an argument.

---

dashboard.el

When dashboard starts up it generates the org-agenda, which it does by opening a bunch of my .org files, which are then pushed to the top of the recentf list.
This change will prevent that by replacing the recentf-list with a copy of the first N items in the recentf-list (so that the recentf widget can display them in the dashboard) and then restoring the original list afterwards (thus discarding the new files that were incidentally added as part of dashboard's rendering)

Don't add org-agenda, etc to the recentf list when dashboard renders

---

README.org
dashboard-widgets.el

Adds face for text banners.
Allowing for colors, font-weight, etc, as referenced in issue #80 
Example
init.el:
```
(set-face-attribute 'dashboard-text-banner-face
nil
:foreground "#FF0BAF"
:weight 'bold
:slant 'italic)
```

fixes #80, adds face for text-banners

---

dashboard-widgets.el

fixes #87 
by removing `:follow-link "C-m"` arguments from all the widget creation calls

fixes #87 - Unwanted `RET` typed into buffer when clicked

---

README.org

Also, all badges point to the proper link to melpa/melpa-stable/CircleCI
The result can be previewed [here](https://github.com/emacs-dashboard/emacs-dashboard/blob/feature/melpa-badges/README.org)

Improve project badges

---

dashboard.el

Centering algorithm wasn't considering the fact that the longest line in the dashboard could be longer than the window width. Which isn't normally a problem. But it was trying to insert a negative amount of spaces LOL.
This fixes https://github.com/emacs-dashboard/emacs-dashboard/issues/98

Handle the case where dashboard lines longer than win width

---

README.org
dashboard-widgets.el
dashboard.el

A small enhancement. Show shortcut indicators (if specified) for each section. Open to suggestions. Useful? Add font-lock?

Add shortcut indicators to sections

---

dashboard-widgets.el

A small fix. I added `dashboard-hackernews` to my dashboard, updated it to call the new `dashboard-insert-section` and it was having trouble generating the symbol for the lambda that is the keyboard jump. Probably because it makes some async calls prior. This seems to solve this issue.

Generate symbol in let. make-symbol failing occasionally in body

---

dashboard.el

The function body for `dashboard-next-section` is contained in the body of the starting `(interactive)` form, whereas it shouldn't be :)
The command still "works" since we try to evaluate the body of `interactive`, but pressing `}` signals an error every time.

Fix error in `dashboard-next-section`

---

dashboard.el

- Add `dashboard-previous-line`, `dashboard-next-line`.
- When moving point up or down a line, move to the beginning of that line’s item.  This lets us move to some line with `C-n`, then press `RET` to open that line’s item immediately.

Make line moving commands behave like `dired`

---

dashboard-widgets.el
dashboard.el

1. Fix #128: Can not select item when using icons.
1. Refactor: remove the advice for dashboard-insert-heading.
1. Use lexical binding to improve performance. 
1. Eliminate compiler warnings.

Make the icons clickable with the file names and performance improvements

---

dashboard-widgets.el

This should fix #136.
I tried to look around to see if there was a very reliable way to determine if package.el is being used. Unfortunately, I didn't really find a foolproof method. This PR is my best attempt at providing something that is somewhat reliable, and it at least solves my issue.
My Emacs and Elisp skills are basically terrible, so feel free to reject this if it's not up to snuff.

Circumvented use of `package-activated-list` if package.el is not used

---

README.org
dashboard-widgets.el

Do not require `all-the-icons` to generate the footer message. Now `dashboard-footer-icon` will only use `all-the-icons` only if the package is available.
Fix #140

Do not require all-the-icons for footer icon, use it only if it is available

---

dashboard-widgets.el

Move `display-graphic-p` check to `dashboard-footer-icon` so the fallback text works properly.

Properly use footer icon fallback text

---

README.org
dashboard-widgets.el

@JesusMtnez @ema2159 , I port the navigator feature from my `Centaur Emacs`. Please review and merge. Thanks!
To show navigator below the banner:
```elisp
(setq dashboard-set-navigator t)
```
To customize the buttons of the navigator like this:
```elisp
;; Format: "icon title help action face"
(setq dashboard-navigator-buttons
`((,(all-the-icons-octicon "mark-github" :height 1.1 :v-adjust 0.0)
"Homepage"
"Browse homepage"
(lambda (&rest _) (browse-url "homepage")))
("★" "Star" "Show stars" (lambda (&rest _) (show-stars)) 'warning)
("?" "Help" "?/h" #'show-help nil)))
```

Add the navigator below the banner with the customized buttons.

---

dashboard-widgets.el

- Use `(bound-and-true-p package-alist)` to check if `package.el` is enabled.
- Use ` (and (boundp 'straight--profile-cache) (hash-table-p straight--profile-cache))` to check if `straight.el` is enabled.
This should fix discussion in https://github.com/emacs-dashboard/emacs-dashboard/pull/138
@romatthe could you please check if this works for you with `straight.el`?
@ema2159 I would also like your opinion on this

Support `straight.el` properly in `dashboard-init-info`

---

README.org
dashboard-widgets.el

Fix #148 .
```elisp
;; Format: "(icon title help action face prefix suffix")
(setq dashboard-navigator-buttons
`(;; line1
((,(all-the-icons-octicon "mark-github" :height 1.1 :v-adjust 0.0)
"Homepage"
"Browse homepage"
(lambda (&rest _) (browse-url "homepage")))
("★" "Star" "Show stars" (lambda (&rest _) (show-stars)) warning)
("?" "" "?/h" #'show-help nil "<" ">"))
;; line 2
((,(all-the-icons-faicon "linkedin" :height 1.1 :v-adjust 0.0)
"Linkedin"
""
(lambda (&rest _) (browse-url "homepage")))
("⚑" nil "Show flags" (lambda (&rest _) (message "flag")) error))))
```

Support multiple lines for the navigator.

---

dashboard-widgets.el
dashboard.el

Do not require `bookmarks`, `calendar` and `register` initially. Instead, they are loaded when needed by a widget.
Partially solve #159

Reduce initial requires

---

dashboard.el

Replace `seq-take` call with its code, to avoid adding `(require seq)`.
Fix #152

Replace `seq-take` with its code

---

dashboard.el

Is this something what you want? #161

Remove `(require 'seq)`

---

README.org
dashboard-widgets.el

Added support for filtering by category in dashboard, so the users can now select the org categories which they wants to have in the dashboard. 
The users would have to specify the category which they need in their dashboard, or if they don't all categories will be considered.
So in my config I have something like this:
```
(use-package dashboard
:ensure t
:config
(setq dashboard-items '((recents . 10) (bookmarks . 5) (agenda . 10)))
(setq dashboard-org-agenda-categories '("Tasks"))
(dashboard-setup-startup-hook))
```

Added filtering by category for org mode

---

dashboard.el

Dashboard return button.

---

dashboard-widgets.el

@JesusMtnez fixed the dashboard widget faces issue (fixes #168). Also, cleaned the code fixing some linting issues moving the pacifier at the top of the file as is more usual.

Fix: Fixed widget face bug. Fixed some linting issues

---

dashboard-widgets.el

Space after comma: "I showed you my source code, pls respond" to "I showed you my source code, pls respond".

Fix space after comma for phrase in dashboard-footer

---

dashboard-widgets.el

Check if all-the-icons is loaded before using it.
Fix https://github.com/seagle0128/.emacs.d/issues/150.

Avoid loading `all-the-icons` prematurely

---

dashboard-widgets.el

Using `defcustom` instead of `defvar`, make `custom-set-variables` work correctly.

Replace defvar with defcustom, making customize work properly

---

dashboard-widgets.el

In general, I think it's a bad idea to calculate `dashboard-footer` or other information that's going to be on the dashbaord in a `defvar` or `defcustom` (any setter) form. This makes these values harder/more annoying to customize. Don't get me wrong you can still customize them, but the calculations will be done before you've even had a chance to decide you want them.

Create a custom variable for dashboard-footer

---

dashboard-widgets.el

The icon `radio-tower` is too big.

Smaller icon size for remote files

---

dashboard.el

If you set `dashboard-items` to nil, `dashboard--section-starts' is nil. The current code tries to get the car of `dashboard--section-starts' and will raise an error if it is nil. This pull request simply checks if `dashboard--section-starts` is nil before getting the car.

Fix error when `dashboard--section-starts' is nil

---

dashboard.el

This is a short ~~one~~two-liner commit to add support for hiding line numbers by default for users of `global-display-line-numbers-mode`, the way they are hidden for users of `global-linum-mode`. It checks the major version first, since the new mode was added in Emacs 26.

Disable display-line-numbers-model

---

dashboard-widgets.el

Mute the annoying `No projects needed to be removed.` message.

Mute no project removed message

---

dashboard-widgets.el

Align the file icons horizontally in dashboard.
Also fix compiler warnings.

Align the file icons horizontally

---

dashboard.el

Sometimes we may have accidentally killed the `\*dashboard\*` buffer.  And then `(kill-buffer dashboard-buffer-name)` will not work and give out an error.  Thus, when the buffer not exists, we can ignore the `kill-buffer` step.

Check if *dashboard* buffer exists or not.

---

dashboard.el

This patch improves the way to identify the page separator. It's a lot accurate and respect the custom variable `dashboard-page-separator`!

Better identify page separator.

---

dashboard-widgets.el

- Makes shortcuts configurable
- Only show shortcuts that are not `nil`
- Use cleaner identifiers for the shortcut lambdas
- Add docstrings to the shortcut lambda (visible with e.g. `C-h k p`)
I'm an elisp novice, any suggestions appreciated :)

Make dashboard shortcuts configurable

---

README.org
dashboard-widgets.el

Commits to refactor the agenda widget.
It show all agenda entries, expose `org-map-entries` `MATCH` parameter.
Allow time format.

Agenda refactor

---

dashboard.el

This could be useful to delay loading of some packages or any time consuming processes to end of the dashboard initialization.
Loading some big packages with this hook reduced my init time (init of dashboard screen actually) from 1.8s to 1.3s. Emacs does not respond before run-hooks finished of course but this feels much faster and I look to the dashboard for a sec anyway. So I think this is an improvement.

Add dashboard-after-initialize-hook to run after initialization

---

dashboard-widgets.el

very minor fix which prevented the registers "e" shortcut from working.

fix registers shortcut

---

dashboard-widgets.el

Logic error, fix not allowing text inside terminal.
See #153.

Allow txt when graphical.

---

dashboard-widgets.el

I think for some reason the `widget-button` doesn't get render correctly. This patch respect the face `widget-button`? 😕

Respect to widget-button face.

---

dashboard-widgets.el

This patch added a custom face for displaying `--- No items ---`. I didn't bother to add the documentation here because I don't think this is the major feature. 
---
@JesusMtnez Let me know what you think! Thanks!

Add custom face for no items

---

README.org
dashboard-widgets.el

Add `dashboard-projectile-switch-function` to custom variables, a function use when switching to projectile projects.
By default is `projectile-switch-project-by-name` but it can be change to `counsel-projectile-switch-project-by-name`, in this case to solve #215 and in my case `projectile-persp-switch-project`.

Define custom function to switch to a project.

---

dashboard-widgets.el

Solves #266
When schedule-time or deadline-time is nil but not both,
org-time-less-p treat them as current-date. Filter will skip the entry
unless it's not done and has schedule time less than due date or has a
deadline time less than due date.
There are other ways to express this condition
```ruby
(when (or (org-entry-is-done-p)
(and (or (null schedule-time)
(org-time-less-p due-date schedule-time))
(or (null deadline-time)
(org-time-less-p due-date deadline-time))))
(point))
```
Or
```ruby
(cond
((org-entry-is-done-p) (point))
((and schedule-time
(org-time-less-p schedule-time due-date)) nil)
((and deadline-time
(org-time-less-p deadline-time due-date)) nil)
(t (point)))
```

Bugfix dashboard-filter-agenda-by-time.

---

dashboard-widgets.el

- The project package built into Emacs 27 is too old; refer to Gnu
Elpa’s version instead.

Clarify docstring of `dashboard-projects-backend`

---

dashboard-widgets.el

This patch does the following.
- Reuse variable `dashboard-footer-messages` to reduce duplicate code
- Add missing document string to variable `dashboard-banners-directory`
- Other minor like `newline`, etc

Minor clean up

---

README.org
dashboard-widgets.el

The discussion here, https://github.com/emacs-dashboard/emacs-dashboard/commit/d7921414dd47ea8eeaa2631cb15f75e31c485eb7.
`widget-button` face is widely use, I think we should create our own custom face to prevent tweaking `widget-button` face.

Respect to custom items face instead of widget-button face

---

dashboard-widgets.el

In `dashboard-insert-image-banner` check also for image transforms
functionality to scale images to `:max-width` / `:max-heigh`

Support for image transforms in newer Emacs

---

Cask
dashboard-widgets.el
dashboard.el

Hmmm... I have tried implements #276. I would say this is a frame so we can implement more styles in the future.
@JesusMtnez What do you think? 😕 
```el
(setq dashboard-path-style 'truncate-middle)
(setq dashboard-path-max-length 50)
```

Add truncate style for path

---

dashboard-widgets.el

Introduces `dashboard-agenda-highlight-headlines` as a Boolean to
highlight agenda headlines using org default faces.
Headlines are highlighted by setting the corresponding
`face` text-property to each part of the headline. Issue #264 shows
that headlines are highlighted only after visit the org buffer and
when org buffer is killed headlines looses their faces.
I couldn't found the function that sets the faces, so now
faces are assigned to the TODO and HEADING parts only if they don't
already had a face.

Agenda highlight headlines

---

dashboard-widgets.el

We need this or else it will insert empty the file path that has been deleted from disk.

Clean up recentf list before insertion

---

dashboard-widgets.el

Forgot to mute the `recentf-cleanup` operation.
@JesusMtnez :)

Mute recent file clean up

---

dashboard-widgets.el

Without this PR, if `dashboard-week-agenda` is `t`, items have "unknown file icon".

Fix icon for week agenda items

---

dashboard.el

Hi, I have been using dashboard for a long time. Thanks for your amazing work and all the contributors.
Recently, I meet the issue that Recent Files show the org-agenda files.
I think #83 don't fix issue #51 perfectly.
#83 only works when the Emacs starts up the first time .
It won't works in the following situations:
1. press `g`(call `dashboard-refresh-buffer`) after you `kill-buffer` all your agenda files.
The reason here is #83 use `origial-recentf-list` to restore the `recentf-list` after ALL dashboard-items HAVE been rendered.
```
save recentf-list -> do agenda -> do other things -> do recentf -> restore recentf-list
```
I think the right thing is
```
save -> do agenda -> restore -> do other things -> restore -> do recentf -> restore
```
So I make this PR.

Fix recent files show org agenda files issue

---

dashboard-widgets.el

This fixes issue #310. The symptom was a bad function call of a let
binding, path, in an if-let*

Add a missing require for subr-x #310

---

dashboard-widgets.el
dashboard.el

Hi, this is for #160
As @Luis-Henriquez-Perez said to keep the lines of page-break-lines it's needed to set `dashboard-page-separator` to "\n\f\n" and have installed page-break-lines (the hook is not needed).

Optional page-break-lines.

---

README.org
dashboard-widgets.el

Closes #305 
Section headings can now be given custom names through `dashboard-item-names'.
Since this is done through overlays it doesn't break any function that expects
the headings to have their default names.
It would arguably be more elegant to adapt all of the aforementioned cases to
use a system that can handle any name, but the work necessary would be a lot
more extensive than this, and I don't know how much of the codebase one would
want to revamp to accommodate this single feature.

Allow section headings to be customized

---

README.org

`page-break-lines` became optional dependency after PR #315.
Update the README file.
---
By the way, @JesusMtnez can you set me as a org owner? or grant me the push permission to this repo? I think this would be a lot easier for me to maintain it! Hope I am qualify enough for the permission! 😅

Update document for optional dependency

---

README.org
dashboard-widgets.el

- Use gif as dashboard banner
- verify if `banner` is a gif
- if yes, animate it
- **obs.:** to do so, I had to add a new way of setting `spec`, I'm not sure why but the way it was before, it was messing the gif quality.
In my configs:
```lisp
(setq dashboard-startup-banner  "path/to/carlton.gif")
```
https://user-images.githubusercontent.com/11412209/134744050-b10904f3-5f6d-4fc7-aa77-882fabe6db5b.mp4

feat: added support for gifs

---

dashboard-widgets.el

This patch fixes an issue where the init info doesn't show the correct value of `emacs-init-time`.
The cause is due the `defcustom` default value being computed at whatever time this package is loaded, which not necessarily represent the final startup time. As example, on my local use-package based setup it reports something around 0.6 seconds, while manually calling `M-x emacs-init-time` does say 2.5 seconds.
The fix is wrapping the default message inside a lambda, to defer computing until render time. This change should keep old behavior, in case any user override `dashboard-init-info` with some fixed string.

Fix init-info reporting wrong `emacs-init-time'

---

README.org

The previous link to the Org mapping documentation gives a 404.

Fix broken URL in README

---

README.org
dashboard-widgets.el

Hi, this is for #326
In org there is [org-agenda-sorting-strategy](https://orgmode.org/worg/doc.html#org-agenda-sorting-strategy) to sort agenda entries.
This PR introduces `dashboard-agenda-sort-strategy` to define the list of strategies for sorting the agenda.
For example, in the case of sorting by time (scheduled) `(setq dashboard-agenda-sort-strategy '(time-up))` will put the entries with time indications first (early first).

Dashboard agenda sort

---

README.org
dashboard-widgets.el

Hi, this is for #339. 
In that case, for a 'LONGLONGCATEGORY' with length 16 the `dashboard-agenda-prefix-format` could be `" %i %16c %-10s "`. I hope the comments on the README file are clear enough. 
Thanks.

Custom dashboard-agenda-prefix-format.

---

dashboard-widgets.el

In emacs the "size" of as hash table refers to how big the table
itself is.  In other words, its capacity.  "count" is for "the actual
number of entries".

correct straight.el package count

---

dashboard-widgets.el

I also modify some code as suggested in #350 
I change `add-to-list` with another `if-let` trying to keep the list `org-agenda-prefix-format` as clean as possible and prevent to keep adding a `'dasboard-agenda` entry each time `dashboard-agenda-prefix-format` change.

Fix #353 space between todo and headline.

---

CHANGELOG.md
dashboard.el

To avoid force loading certain modules to increase startup time.

Lazy load it's module

---

dashboard-widgets.el
dashboard.el

Hi, this is the implementation of `dashboard-remove-item-agenda`, it calls `org-todo`  with the entry at point and if the `todo-state` is changed to `DONE` (or any filter state) then the entry is removed for the dashboard.

Agenda remove item

---

dashboard-widgets.el

`length` cannot compute the width of a string on display, so the footer may not be at the center of the screen  when its language is not English,

Use `string-width` to compute the width of the dashboard footer

---

dashboard-widgets.el

Add support for the number of packages from Elpaca.

Support `Elpaca` in `dashboard-init-info`

---

CHANGELOG.md
dashboard-widgets.el

Calculate string length in pixel instead of the function `(length ...)`.

fix(dashboard-widget.el): Calculate path length in pixel

---

dashboard-widgets.el

Don't `(require 'shr)` if possible.

refactor(dashboard-widgets.el): Prevent loading shr if not needed

---

README.org
dashboard-widgets.el
dashboard.el

This patch contains two (entangled) fixes:
1. Center the banner with text properties.
2. Display both the image and text banner at the same time, letting the frame pick the right one for the display type.
The first change, centering with text properties, ensures that the text is smoothly centered without flickering, even if the dashboard is displayed in multiple windows at the same time (each window will center independently).
I'm inserting both the text and image banner at the same time to ensure that we always get the correct banner. Before this change, creating the dashboard buffer before creating a GUI frame would display a text banner.
Known issue: This patch still has to pick whether to center by the image or by the text banner. It does this at redisplay time using a display …

Center banner with properties and combine text with image

---

dashboard-widgets.el

Use `image-type-available-p` and `image-type` instead of `image-supported-file-p` as that function only exists in Emacs 29.

Restore Emacs 26 support

---

dashboard-widgets.el

Avoid `(pred (not` as it isn't supported before Emacs 28.

---

dashboard-widgets.el

Current function dashboard-filter-agenda-by-time allows all past agenda items to show.
This means all past items are passed.
This filters agenda items, and passes them only if an associated date is after current date.
This makes sure the items are relevant to the current time period, making sure they either start or end in the current week and not at some point in the past.

Fixed issue wherein all previous entries showed.

---

dashboard-widgets.el

This is for #434. Now always apply `org-outline-level` face, and also apply :height inherit from `dashboard-items-face` or from the `default` face.

Inherit height on agenda entries from dashboard-items-face.

---

dashboard-widgets.el

Should close #404.
I have done some rudimentary testing. `(put-text-property (point) (point-max) 'face 'dashboard-text-banner)` seems to not format the text added through `insert` in line 597. Why that’s the case, I unfortunately do not know. Any tips are welcome.

Add ascii option to dashboard-startup-banner

---

README.org

I struggled trying to find how to display the dashboard. This adds one sentence to the readme with a reference to dashboard-refresh-buffer

Added reference to dashboard-refresh-buffer  in readme file

---

README.org
dashboard.el

1) autoloading the `dashboard-refresh-buffer` function so it can be available before the dashboard has been displayed.
This should allow users to decide whether they want to display the dashboard by default at startup. If they don't, they can delay loading the whole package, and still be able to open the dashboard whenever they want
2) renaming `dashboard-refresh-buffer` to `dashboard-open` to better suggest the above use of the function. `dashboard-refresh-buffer` is kept as an alias for consistency and backwards compatibilty.

dashboard-open

---

dashboard-widgets.el

See comments in #436.
Due to a discrepancy in point behavior between `insert` and `insert-file-contents`, `insert` must be called in a `save-excursion` block to ensure that the point remains unchanged.

Fix spillover bug from #436

---

README.org
dashboard-widgets.el

Hi, this is for #405.
It defines a custom variable, dashboard-agenda-tags-format, that is pointing to a function that be applied to the tag strings "tag1:tag2:tag3".
It also defines dashboard-agenda--show-tags a function that return the tags, and dashboard-agenda--hide-tags a function that returns nil, so tags are ignored.

Agenda tags format.

---

dashboard-widgets.el

Closes #333.
Adds a customizeable function to restrict icon insertion and default it to display-graphic-p to retain legacy behavior. This will let terminal users who have icons properly configured use dashboard with icons without needing local modifications.

Make icon display predicate customizeable

---

dashboard-widgets.el
dashboard.el

This code was introduced before lexical binding was in use, so I suspect it used to work. Currently it causes the read-only status of the dashboard buffer to never be set, as only the lexical variable gets set instead.
I believe the original intention was to allow writing into the read-only buffer when generating it. `inhibit-read-only` should be a superior solution.

Make the dashboard buffer read-only, as originally intended

---

.gitignore
README.org
dashboard-widgets.el

Addressing #444, icons can be added to custom headers through an optional argument (which leaves the original `dashboard-insert-heading` function compatible and equally operational as before).
Also adds ignore to MacOS temp `.DS_Store` files.

Adding ability and docs for icons in custom widget headers.

---

dashboard-widgets.el

The reported time would be the time needed only to the queue the packages, not to actually process them.

feat(elpaca): provide a semantically correct init time in init info

---

dashboard-widgets.el

**demo**
(Ubuntu 20.04, Gnome Desktop, Alacritty terminal, FiraCode Nerd Fonts)
**Major Changes**
I added `dashboard-icon-type` which specifies which icon package to use (either `'all-the-icons` or `'nerd-icons`). Based on `dashboard-icon-type`, other icon related custom variables such as `dashboard-heading-icons` will have corresponding default values. 
**Configuration for using Nerd Icons**
```elisp
(setq dashboard-display-icons-p t) ;; to use icons under terminal
(setq dashboard-icon-type 'nerd-icons)
```
**Things I am not sure about**
I'm not sure if my implementation for setting default values for some custom variables based on `dashboard-icon-type` is good. Let's say I set `dashboard-icon-type` to `'nerd-icons`. My current implementation for setting the default value of …

add nerd-icons support to dashboard

---

CHANGELOG.md
dashboard-widgets.el

Introduce two new custom variables `dashboard-heading-icon-height` and `dashboard-heading-v-adjust`.

feat(icons): Add custom arguments for icons

---

dashboard-widgets.el

Nerd Fonts recently released [3.0 version](https://github.com/ryanoasis/nerd-fonts/releases) and I also updated [nerd-icons.el](https://github.com/rainstormstudio/nerd-icons.el). Some `nf-oct-*` icons are removed so they need to be changed to `nf-cod-*` icons with same/similar names.

use Nerd Fonts 3.0 icons

---

dashboard.el

The commit partially revert 48860b1 by re-adding the dashboard-resize-on-hook function and its setup hook.
The setup hook has also been moved into the dashboard-setup-startup-hook function.
Fixes #433.

fix: dashboard not appearing on startup

---

dashboard.el

dashboard-initialize: Replaces lambda added to emacs-startup-hook.
See: #474

dashboard-setup-startup-hook: add named functions to hooks

---

README.org
dashboard-widgets.el

Add option for image banner, xbm file from: https://github.com/meritamen/.emacs.d/blob/master/banners/evil.xbm
```
(dashboard-startup-banner (expand-file-name "banners/evil.xbm" user-emacs-directory)
```

Add xbm support for dashboard-startup-banner

---

dashboard.el

This PR adds an option to hide the cursor while in `dashboard-mode`. This is nice for users who disable all of the menu options.
Before:
After:

Add customization option to hide the cursor on the dashboard

---

dashboard.el

This PR adds an option to vertically center the dashboard content. I tested it with a few different dashboard configurations on MacOS and everything seems to be working.
Before:
After:

Add option to vertically center dashboard

---

README.org
dashboard-widgets.el
dashboard.el

Hello,
I made this patch that include some
features to dashboard:
- Support for insert startupify list in order,
this adds more customization to dashboard.
- Support for solaire-more.
- Bugs fix to some defcustom types.
I would like to hear your thought and reviews about this patch.
Thanks.

Support for insert startupify list in order, support for solaire mode and more.

---

README.org
dashboard-widgets.el
dashboard.el

As Explained here:
https://github.com/emacs-dashboard/emacs-dashboard/issues/508
User Options like: dashboard-set-footer, dashboard-set-navigator and dashboard-set-init-info
are unnecessary and can be replaced by dashboard-startupify-list, this patch do this job.

Deprecate unnecessary user options.

---

README.org
dashboard.el

I've noticed that using dashboard-after-initialize-hook with solaire doesn't fix banner image background issue.
I found that this is because the banner is created before solaire is called.
The solution i found is making other hook that just run before dashboard buffer is created.
I wonder if this is a can a good idea or just run dashboard-after-initialize-hook in dashboard--with-buffer.
Also i've noticed moving solaire first in dashboard-startupify-list fix this too.

Add new hook for dashboard.

---

dashboard-widgets.el

Hi,
this is a PR for #489. It fixes the customization type for `dashboard-items` and `dashboard-item-shortcuts`.

Fix type of `dashboard-items` and `dashboard-item-shortcuts`.

---

FAQ.org
README.org
dashboard-widgets.el
dashboard.el

This patch adds optional support for insert arguments into dashboard-startupify-list, this allow insert amount newlines in dashboard-insert-newline, and add into README how to hide modeline.
Also this updates dashboard-items for optionally insert list size.

Support for arguments in dashboard-startupify-list and add FAQ

---

dashboard-widgets.el

The previous type is wrong, as it's for a list of alists, rather than a single alist.

Fix custom type for dashboard-heading-icons

---

dashboard.el

When moving my frame without resizing I expect the logic for vertical centering to give the same result before and after. This currently does not seem to be the case. 
Try setting `dashboard-vertically-center-content` to `t` and then open a new frame. The resulting height of the dashboard depends on the y-coordinate of the frame because `window-absolute-pixel-position` does not give coordinates relative to the frame.
I work around this by subtracting the height "above" my frame. Note that `(point-min)` may not be visible in the frame. Then `(window-absolute-pixel-position (point-min))` evaluates to `nil` which stops the vertical alignment. This seems fine to me as in this case the content does not fit inside the frame anyway.
I noticed this while Emacs was running with XWayland, but I …

Fix vertical offset for centering

---

README.org
dashboard-widgets.el

This PR adds support for tweaking the height and v-adjust of file icons. It aligns with the existing parameters
`dashboard-heading-icon-height` and `dashboard-heading-icon-v-adjust` which work similarly for heading icons.
Defaults are set to the previous defaults.
Let me know if there are any changes needed. :slightly_smiling_face:

feat: Parameters for file icon height and v-adjust

---

CHANGELOG.md
dashboard-widgets.el
docs/FAQ.org
docs/variables-and-functions.org

Also, change defcustom to defun in `dashboard-init-info`, this remove the possibility to customize a text when `dashboard-insert-init-info` but there is `dashboard-banner-logo-title` which is more suitable for that purpose.

Fix #566 to show "installed packages" instead of "loaded packages".
