- dashboard.el
Simple, I don't think I can say a lot here.
> Move page separator to a `Custom` option

- dashboard.el
Hitting "g" on the *dashboard* will redraw its contents, including any
updates to the recent file list.
> Add "refresh" capability

- dashboard.el
The key bindings somewhat mimic the default key binding of vanilla Emacs’
paragraph movement commands, `forward-paragraph` and `backward-paragraph`.
> Add commands to jump between sections

- README.org
- dashboard-widgets.el
**WARNING** This is not fully working yet, I just wanted to let you know I’m working on it.
TODO:
* The items don’t do anything yet; they should jump to the corresponding Org heading
* LIST-SIZE is not respected when rendering the list.  Actually, I don’t know if such limitation should be added or not.
> [WIP] Insert agenda items for the current day

- dashboard-widgets.el
This fixes two issues when populating the list of today’s due agenda entries.
> Fix agenda due-date issues

- README.org
Ref: https://www.reddit.com/r/emacs/comments/8i2ip7/emacs_dashboard_emacsclient/
> Document how to set up with emacs daemon

- README.org
This will automatically install the package.
> Update README to include `:ensure` keyword in `use-package` instructions

- README.org
> Fix typo in configuration

- dashboard-widgets.el
This also documents each shortcut so it doesn't show `??` in the keymap docs
> Fix shortcut regression bug

- dashboard-widgets.el
- dashboard.el
Fixes https://github.com/emacs-dashboard/emacs-dashboard/issues/100
> Fix opening org mode "links"

- dashboard-widgets.el
For any section that has no items, indicate that with `--- no items ---`
Addresses https://github.com/emacs-dashboard/emacs-dashboard/issues/105
> Indicate when a section has no items

- dashboard-widgets.el
This should resolve https://github.com/emacs-dashboard/emacs-dashboard/issues/112. Thanks @seagle0128!
> No need to launch 'projectile-mode

- dashboard.el
Addresses https://github.com/emacs-dashboard/emacs-dashboard/issues/95
> Use "Applications" group and give a proper description

- README.org
- dashboard-widgets.el
New init info customization with a customizable variable that by default displays the packages loaded and the init time
> Added new init info functionality

- dashboard-widgets.el
> Support bookmark/agenda/register/project actions.

- README.org
- dashboard-widgets.el
The heading icons were hard coded so I made them into a customizable alist with a a function  to modify just the icons that the user wants.
> Made heading icons a customizable variable

- dashboard-widgets.el
I think you should have a line at the end of the `*dashboard*` buffer?
> Add newline at the end of insert footer.

- dashboard.el
> Disable undo history for dashboard buffer

- .circleci/config.yml
- .emacs/init.el
- dashboard-widgets.el
> Fix CI and include emacs 27

- README.org
Update documentation on how to change `footer` message.
Close to #219 
@seagle0128 @jcs090218 :eyes:
> Update footer documentation

- dashboard-widgets.el
> Fix typo in footer messages

- dashboard-widgets.el
- dashboard.el
This patch fixes #176 and some clean up like simplifying logic and syntax.
> Some clean up

- dashboard-widgets.el
This PR is the same as #192 and trying to fix #191.
> Fixed of #191, duplicate as #192.

- README.org
- dashboard-widgets.el
This is the same as #157. I opened another PR because the old PR has been a while and I have deleted the branch.
> Text startup banner.

- dashboard.el
> Use when instead if.

- dashboard-widgets.el
> Ensure image when isn't inside terminal.

- dashboard-widgets.el
I think this should fix issue for #252.
> Improve check for dashboard banner.

- dashboard-widgets.el
- dashboard.el
@JesusMtnez What do you think about this?
> Update copyright info.

- dashboard-widgets.el
I think is good to clean up some code after few PRs. ;)
> Some cleanup after few PRs.

- dashboard-widgets.el
I consider this as a much cleaner version.
@JesusMtnez Can you test it for me? Thanks! 😄
> Clean up init info.

- dashboard-widgets.el
I suggest these changes after #233. ;)
> Minor organization for init info.

- dashboard-widgets.el
- Create a menu of none or function
- Document what arguments the function takes
> Fix defcustom of dashboard-projects-switch-function

- dashboard-widgets.el
- Add function to filter agenda entries by todo state
- Change agenda filter customize widget type to choice
> feat: Agenda filter todo

- dashboard-widgets.el
Some minor fix for #279.
@JesusMtnez Sorry, I should have tested this patch more carefully! 😖
> Minor fix for the patch truncate style

- dashboard.el
This should resolve issue #184. This PR is duplicate from #282 but only removing the `widget-button-click`.
> Remove widget-button click.

- dashboard-widgets.el
- dashboard.el
The fix from #283 isn't perfect, revert and attempt for next fix.
Reopen issue #184.
> Revert and use mouse-1 instead

- dashboard.el
This should resolve issue #286.
> Fix mouse track movement by widget-button-click on keymap mouse-1

- dashboard-widgets.el
- dashboard.el
Update license year to new year 2021!
> Update license year

- dashboard.el
I prefer not to kill the buffer and just refresh it with a flag.
> Add flag for force refresh

- README.org
- dashboard-widgets.el
> Release buffers after populate agenda

- dashboard-widgets.el
- dashboard.el
Just some improvements and clean up. :)
> Some improvement and clean up

- dashboard-widgets.el
> Fix last patch, bookmarks

- README.org
- dashboard-widgets.el
> Update document, and remove unused variable

- dashboard-widgets.el
- dashboard.el
Try to remove `(require 'seq)` for very little of speed up.
> Use same subseq

- dashboard.el
> Use revert-buffer-function

- .github/workflows/ci.yml
- Cask
- Eask
- Makefile
> Replace Cask with Eask

- .github/workflows/ci.yml
- CHANGELOG.md
- Eask
- dashboard-widgets.el
- dashboard.el
> Add functionality to delete items

- dashboard-widgets.el
- dashboard.el
Very minor clean up for `recentf`.
> Clean up recentf and mute on startup

- CHANGELOG.md
- README.org
- dashboard.el
- test/activate.el
> fix(daemon): Fix dashboard not showing up in daemon mode

- README.org
- dashboard-widgets.el
> Add priority to agenda sort strategies.

- dashboard-widgets.el
> Fix dashboard banner face

- dashboard-widgets.el
I made a last minute change here and forgot a dot...
fixes #413
> Fix dashboard centering when both an image and text are specified

- dashboard-widgets.el
> fix: don't assume that PNGs are supported

- dashboard-widgets.el
- dashboard.el
For #419, and also some clean up
> Workaround for incorrect center text calculation 

- dashboard.el
Also active `inhibit-redisplay`.
> Use non-interactive for deleting char

- dashboard-widgets.el
- dashboard.el
Leave 2 lines before footer, not 3.
> fix: Revert display newline on footer

- .dir-locals.el
- CHANGELOG.md
- dashboard-widgets.el
> fix(centering): Caculate line length in pixel width

- dashboard.el
> fix: Make sure we don't interfere init-info

- CHANGELOG.md
- dashboard-widgets.el
> refactor(widget): Minor code cleanup

- README.org
I added some information about how to use `nerd-icons` in README.
> add info about nerd icons to README

- CHANGELOG.md
- Eask
- dashboard-widgets.el
> fix: Make remove entry optional

- dashboard-widgets.el
> Add dashboard icon face.

- dashboard-widgets.el
This should be helpful to #481, I can display transparent images with setting it to '(:mask heuristic).
> add `dashboard-image-extra-props' option.

- dashboard-widgets.el
I think i got around this #501. I am a beginner at lisp. I just took help from google and LLM and fixed the issue for me. Check if its a good approach to this problem.
> Fixed: Adding anmiation to webp image.

- README.org
- dashboard-widgets.el
Hello, this patch allow to users display random banners in a list.
I'd like to hear their reviews.
> Support for random banners.

- dashboard-widgets.el
Fixes: https://github.com/emacs-dashboard/emacs-dashboard/issues/515
> Fixes to dashboard banner.

- FAQ.org
- dashboard-widgets.el
This play well and makes sense with `random-footer-messages`
> Support for random footer icon

- dashboard-widgets.el
> Fix sorting by priority in agenda

- dashboard.el
Dashboard-open use dashboard--with-buffer and switch to it before inserting the startupify list.
Remove dashboard-force-refresh and pass it as optional argument to force-refresh the buffer.
> Fix vertically-center.

- README.org
> correct cons option dashboard-startup-banner in README

- README.org
- dashboard.el
- variables-and-functions.org
- created full variables and functions documentation, with examples
- Added cycle forward and cycle backwards functions
- fixed dashboard-previous-section docstring
> Added documentation and dashboard-cycle-section-forward and dashboard-cycle-section-backward

- dashboard.el
Dashboard Widgets are buggy on Emacs Android .
This patch must fix this.
> Add support for click widgets in touchscreen.
